version: "3.3"




services:
  robot_api:
    build:
      context: .
      dockerfile: ./TibberTask/Dockerfile
    ports:
      - 5000:80
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  pgadmin: 
    image: dpage/pgadmin4
    ports: 
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: arla@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgdata:
  pgadmin-data:


